---
toc: false
---

## Education

**Vanderbilt University**, Nashville (TN), USA

PhD in Biostatistics \| 2018 - 2023. Advisers: Jonathan Schildcrout, PhD and Ran Tao, PhD

**University of British Columbia**, Vancouver (BC), Canada

MSc in Statistics \| 2013 - 2015. Adviser: Gabriela Cohen Freue, PhD

Thesis Title: "Instrumental Variable Selection: a Comparison of Regularisation and Post-Regularisation Methods"

**Sapienza University of Rome**, Rome, Italy

MSc in Actuarial and Financial Science \| 2010 - 2013. Adviser: Paola Verico, PhD. Conferred cum laude

BSc in Statistics, Finance and Insurance \| 2006 - 2009. Conferred cum laude

## Experience

**Vanderbilt University, Department of Biostatistics, Nashville (TN), USA**

-   Research Assistant \| June 2019 - Present

    -   Developed designs and analysis methods for cost and resource efficient studies in longitudinal data settings. Advisers: Jonathan Schildcrout, PhD and Ran Tao, PhD

    -   Provided statistical analyses for the Vanderbilt Inpatients Cohort Study (VICS). Advisers: Jonathan Schildcrout, PhD and Sunil Kripilani, MD

    -   Member of the Statistical Innovation in Clinical Trials Working Group

    -   Worked on ways to integrate randomized controlled trials and observational data. Adviser: Amir Asiaee, PhD

-   Teaching Assistant \| January 2019 - Present

    -   DS5440 Data Science Algorithm (Fall 2020, 2021, 2022). Instructor: Diego Mesa, PhD

    -   BIOS7330 Regression Modelling Strategies (Spring 2022). Instructor: Frank Harrell, PhD

    -   BIOS7632 Advanced Statistical Inference (Statistical Learning) (Spring 2021). Instructor: Matt Shotwell, PhD

    -   MSCI Biostatistics II (Spring 2020). Instructors: Thomas Stewart, PhD and Frank Harrell, PhD

    -   BIOS6301 Introduction to Statistical Computing (Fall 2019). Instructor: Cole Beck, BSc

    -   BIOS6312 Modern Regression Analysis (Spring 2019). Instructor: Robert Johnson, PhD

**MRC Lifecourse Epidemiology Unit, Southampton, UK**

-   Statistician \| September 2015 - July 2018

    -   Statistician for the "Nutrition, Development and Lifelong Health in Transitioning Populations" programme

    -   Provided statistical analysis for multiple studies within the programme. Research included modelling fetal and childhood growth to study associations between early life characteristics and risk of cardio-metabolic disease in later life

    -   Member of the Epigenetic Mechanism link Pre-conceptional nutrition and Health Assessed in India and Sub-Saharan Africa group. [EMPHASIS Website](https://www.emphasisstudy.org)

**The University of British Columbia, Vancouver (BC), Canada**

-   Teaching Assistant \| September 2013 - August 2015

    -   STAT300 Intermediate Statistics for Applications (Fall 2013, 2014). Served as Head TA during Fall 2014. Instructors: Bruce Dunham, PhD and Lang Wu, PhD

    -   STAT200 Elementary Statistics for Applications (Spring 2014, 2015, Summer 2015). Served as Head TA during Summer 2015. Instructor: Eugenia Yu, MSc
